DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS TEAMHIERARCHY;
DROP TABLE IF EXISTS USERACCESS;
  
CREATE TABLE USERS (
  empid VARCHAR(50) NOT NULL,
  accesskey VARCHAR(50) NOT NULL,
  country VARCHAR(50) NOT NULL
);

CREATE TABLE TEAMHIERARCHY (
  empid VARCHAR(50) NOT NULL,
  managerid VARCHAR(50) NOT NULL
);

CREATE TABLE USERACCESS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  empid VARCHAR(50) NOT NULL,
  accesskey VARCHAR(50) NOT NULL,
  country VARCHAR(50) NOT NULL,
  subuser VARCHAR(50) NOT NULL,
  subuseraccesskey VARCHAR(50) NOT NULL,
  subusercountry VARCHAR(50) NOT NULL
);