DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS TEAMHIERARCHY;
DROP TABLE IF EXISTS USERACCESS;
  
CREATE TABLE USERS (
  UID INT AUTO_INCREMENT PRIMARY KEY,
  emp_id VARCHAR(50) NOT NULL,
  access_key VARCHAR(50) NOT NULL,
  country VARCHAR(50) NOT NULL
);

CREATE TABLE TEAMHIERARCHY (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  EMP_ID VARCHAR(50) NOT NULL,
  MANAGER_ID VARCHAR(50) NOT NULL
);

CREATE TABLE USERACCESS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  emp_id VARCHAR(50) NOT NULL,
  access_key VARCHAR(50) NOT NULL,
  country VARCHAR(50) NOT NULL,
  sub_user VARCHAR(50) NOT NULL,
  sub_user_access_key VARCHAR(50) NOT NULL,
  sub_user_country VARCHAR(50) NOT NULL
);

